name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            env:
              ASAN: "yes"
            shell: bash
          - os: macos-latest
            shell: bash
            env:
              LDFLAGS: "-L$(brew --prefix readline)/lib"
              CPPFLAGS: "-I$(brew --prefix readline)/include"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    steps:
    - uses: actions/checkout@v4
      with: { submodules: true }
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get -y install pkg-config gettext autopoint libfuse-dev libattr1-dev
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install coreutils readline pkg-config automake gettext macfuse
        # Prepend optional brew binary directories to PATH
        echo "$(brew --prefix coreutils)/libexec/gnubin:$(brew --prefix m4)/bin:/usr/local/opt/gettext/bin" >> $GITHUB_PATH
    - name: Build
      run: ./build-aux/build.sh
